// TODO(ai-review): review for style and correctness
//! Integration test: build a tiny DLL with the `Constants.GAME_VERSION`
//! const-string shape that older Unity games carry their real version in
//! and verify the extractor reads it back. The DLL is generated by
//! `tests/fixtures/Makefile`; run it once after editing `sample.cs`.

#![cfg(feature = "unity")]

use transform::unity::game_version::extract_game_version;

#[test]
fn extract_game_version_from_synthetic_dll() {
    let dll = std::fs::read("tests/fixtures/game_version/sample.dll")
        .expect("fixture missing — run `make` in tests/fixtures");
    let version = extract_game_version(&dll).expect("extract_game_version returned None");
    assert_eq!(version, "1.5.78.11833");
}

#[test]
fn returns_none_when_constant_absent() {
    // The SecurePlayerPrefs fixture has no `Constants.GAME_VERSION` — the
    // extractor must parse it without error and report nothing.
    let dll = std::fs::read("tests/fixtures/secure_player_prefs/sample.dll")
        .expect("fixture missing — run `make` in tests/fixtures");
    assert_eq!(extract_game_version(&dll), None);
}
