// TODO(ai-review): review for style and correctness
//! Integration test: build a tiny DLL with the exact field-initializer
//! shape `SecPlayerPrefs.SecurePlayerPrefs.keyArray` has in a real
//! Unity game and verify the extractor reads the key back. The DLL
//! itself is generated by `tests/fixtures/Makefile` (a thin wrapper
//! around `dotnet build`); run it once after editing `sample.cs`.

#![cfg(feature = "unity")]

use aes::cipher::BlockModeEncrypt;
use transform::unity::secure_player_prefs::{decrypt, extract_key};

const KEY: &[u8] = b"UKu52ePUBwetZ9wNX88o54dnfKRu0T1l";

#[test]
fn extract_key_from_synthetic_dll() {
    let dll = std::fs::read("tests/fixtures/secure_player_prefs/sample.dll")
        .expect("fixture missing — run `make` in tests/fixtures");
    let key = extract_key(&dll).expect("extract_key returned None");
    assert_eq!(key, KEY);
}

#[test]
fn decrypt_roundtrip_matches_securecplayerprefs_encoding() {
    // Hand-built ciphertext using the canonical 32-byte key and the
    // C# `RijndaelManaged { Mode = ECB, Padding = PKCS7 }` defaults.
    // Plaintext is `<r>hi</r>` — short enough to fit one AES block.
    use aes::cipher::KeyInit;
    use aes::cipher::block_padding::Pkcs7;
    use base64::prelude::*;

    let plain = "<r>hi</r>";
    let cipher = ecb::Encryptor::<aes::Aes256>::new_from_slice(KEY).unwrap();
    let mut buf = vec![0u8; plain.len() + 16];
    let ct = cipher
        .encrypt_padded_b2b::<Pkcs7>(plain.as_bytes(), &mut buf)
        .unwrap();
    let blob = BASE64_STANDARD.encode(ct);

    let decrypted = decrypt(KEY, &blob).expect("decrypt returned None");
    assert_eq!(decrypted, plain);
}

#[test]
fn decrypt_returns_none_on_bogus_blob() {
    // Wrong key length — decryptor construction fails up-front.
    assert!(decrypt(b"too-short", "AAAA").is_none());
    // Right key, garbage blob — base64 decode succeeds (zero bytes),
    // but the empty ciphertext can't yield PKCS7-padded output.
    assert!(decrypt(KEY, "").is_none());
}
