/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppsAppidRouteImport } from "./routes/apps.$appid";
import { Route as AppsAppidIndexRouteImport } from "./routes/apps.$appid.index";
import { Route as AppsAppidDepotsDepotIdManifestsGidRouteImport } from "./routes/apps.$appid.depots.$depotId.manifests.$gid";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppsAppidRoute = AppsAppidRouteImport.update({
  id: "/apps/$appid",
  path: "/apps/$appid",
  getParentRoute: () => rootRouteImport,
} as any);
const AppsAppidIndexRoute = AppsAppidIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppsAppidRoute,
} as any);
const AppsAppidDepotsDepotIdManifestsGidRoute =
  AppsAppidDepotsDepotIdManifestsGidRouteImport.update({
    id: "/depots/$depotId/manifests/$gid",
    path: "/depots/$depotId/manifests/$gid",
    getParentRoute: () => AppsAppidRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/apps/$appid": typeof AppsAppidRouteWithChildren;
  "/apps/$appid/": typeof AppsAppidIndexRoute;
  "/apps/$appid/depots/$depotId/manifests/$gid": typeof AppsAppidDepotsDepotIdManifestsGidRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/apps/$appid": typeof AppsAppidIndexRoute;
  "/apps/$appid/depots/$depotId/manifests/$gid": typeof AppsAppidDepotsDepotIdManifestsGidRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/apps/$appid": typeof AppsAppidRouteWithChildren;
  "/apps/$appid/": typeof AppsAppidIndexRoute;
  "/apps/$appid/depots/$depotId/manifests/$gid": typeof AppsAppidDepotsDepotIdManifestsGidRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/apps/$appid"
    | "/apps/$appid/"
    | "/apps/$appid/depots/$depotId/manifests/$gid";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/settings" | "/apps/$appid" | "/apps/$appid/depots/$depotId/manifests/$gid";
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/apps/$appid"
    | "/apps/$appid/"
    | "/apps/$appid/depots/$depotId/manifests/$gid";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  AppsAppidRoute: typeof AppsAppidRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/apps/$appid": {
      id: "/apps/$appid";
      path: "/apps/$appid";
      fullPath: "/apps/$appid";
      preLoaderRoute: typeof AppsAppidRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/apps/$appid/": {
      id: "/apps/$appid/";
      path: "/";
      fullPath: "/apps/$appid/";
      preLoaderRoute: typeof AppsAppidIndexRouteImport;
      parentRoute: typeof AppsAppidRoute;
    };
    "/apps/$appid/depots/$depotId/manifests/$gid": {
      id: "/apps/$appid/depots/$depotId/manifests/$gid";
      path: "/depots/$depotId/manifests/$gid";
      fullPath: "/apps/$appid/depots/$depotId/manifests/$gid";
      preLoaderRoute: typeof AppsAppidDepotsDepotIdManifestsGidRouteImport;
      parentRoute: typeof AppsAppidRoute;
    };
  }
}

interface AppsAppidRouteChildren {
  AppsAppidIndexRoute: typeof AppsAppidIndexRoute;
  AppsAppidDepotsDepotIdManifestsGidRoute: typeof AppsAppidDepotsDepotIdManifestsGidRoute;
}

const AppsAppidRouteChildren: AppsAppidRouteChildren = {
  AppsAppidIndexRoute: AppsAppidIndexRoute,
  AppsAppidDepotsDepotIdManifestsGidRoute: AppsAppidDepotsDepotIdManifestsGidRoute,
};

const AppsAppidRouteWithChildren = AppsAppidRoute._addFileChildren(AppsAppidRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AppsAppidRoute: AppsAppidRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
